### PR TITLE
Fix tests on Python 3.13

### PR DESCRIPTION
**Pull request by hroncok**
This is a followup for d95cc228ea96feec105592a9902e5b2d6cc048a9

### CODE REVIEW

**Comment by hroncok** [comment]
Alternatively, this can be split into a skipped test. Let me know if you prefer that.

**Comment by hroncok** [comment]
The if-ed block seems to be already tested in `test_typeddict_special_keyword_names` so I am not sure what was the purpose :confused:

**Comment by hroncok** [comment]
The `test_keywords_syntax_raises_on_3_13` test already asserts that type error.

**Comment by JelleZijlstra** [comment]
You're right. Let's just remove this block of tests, it duplicates `test_basics_keywords_syntax` exactly.

**Comment by hroncok** [comment]
Done. Explained the reasons for removal in the commit message.

**Review by JelleZijlstra — APPROVED** [review]

**Comment by hroncok** [comment]
Thanks for the quick feedback loop :)

**Pull request merged**
