### PR TITLE
Update LICENSE file

### PR DESCRIPTION
**Pull request by srittau**
This integrates some changes from the CPython repository:

* Update the copyright years.
* Update some wording in the history introduction.
* Change capitalization of the word "internet".

### CODE REVIEW

**Comment by gvanrossum** [comment]
Are there remaining differences with the cpython license left?

**Comment by gvanrossum** [comment]
And whatever we do here should be done to typing too, right?

**Comment by srittau** [comment]
I'll send a PR for typing as well. Here's a diff for remaining changes

```diff
--- LICENSE	2022-08-03 16:40:41.998187611 +0200
+++ ../cpython/LICENSE	2022-05-03 13:41:18.466707570 +0200
@@ -59,6 +59,17 @@
 B. TERMS AND CONDITIONS FOR ACCESSING OR OTHERWISE USING PYTHON
 ===============================================================
 
+Python software and documentation are licensed under the
+Python Software Foundation License Version 2.
+
+Starting with Python 3.8.6, examples, recipes, and other code in
+the documentation are dual licensed under the PSF License Version 2
+and the Zero-Clause BSD license.
+
+Some software incorporated into Python is under different licenses.
+The licenses are listed with code falling under that license.
+
+
 PYTHON SOFTWARE FOUNDATION LICENSE VERSION 2
 --------------------------------------------
 
@@ -252,3 +263,17 @@
 WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT
 OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
+
+ZERO-CLAUSE BSD LICENSE FOR CODE IN THE PYTHON DOCUMENTATION
+----------------------------------------------------------------------
+
+Permission to use, copy, modify, and/or distribute this software for any
+purpose with or without fee is hereby granted.
+
+THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
+REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
+AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
+INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
+LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
+OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
+PERFORMANCE OF THIS SOFTWARE.
```

The zero-clause license makes no sense for this repo, but *would* make sense for the typing repo. But this is probably something we should discuss over there. We could add the first sentence here, though:

> Python software and documentation are licensed under the
> Python Software Foundation License Version 2.

**Comment by gvanrossum** [comment]
That makes sense but probably won’t satisfy that tool. An alternative might be the PSF-2.0 license from that tool’s repo but we’d have to all agree on it and review it.

**Review by gvanrossum — APPROVED** [review]

**Comment by JelleZijlstra** [comment]
To satisfy the tools, it's probably best to match CPython's LICENSE file exactly, isn't it?

**Comment by gvanrossum** [comment]
Dunno, it looked like CPython was also categorized as OTHER…

**Comment by srittau** [comment]
Honestly, I don't think we should add "useless" parts to the license file just to satisfy some license checking tools. This just makes it harder to understand for human consumption and has the chance to make it legally muddier.

**Pull request merged**
