### PR TITLE
Expand the pyproject.toml sdist include expression to include src/_typed_dict_test_helper.py

### PR DESCRIPTION
**Pull request by hegjon**
### Before
```
typing_extensions on  main via 🐍 v3.10.8
❯ python3 -m build .
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (flit_core >=3.4,<4)
* Getting dependencies for sdist...
* Building sdist...
* Building wheel from sdist
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (flit_core >=3.4,<4)
* Getting dependencies for wheel...
* Building wheel...
Successfully built typing_extensions-4.4.0.tar.gz and typing_extensions-4.4.0-py3-none-any.whl

typing_extensions on  main via 🐍 v3.10.8 took 4s
❯ tar tzf dist/typing_extensions-4.4.0.tar.gz
typing_extensions-4.4.0/CHANGELOG.md
typing_extensions-4.4.0/LICENSE
typing_extensions-4.4.0/README.md
typing_extensions-4.4.0/pyproject.toml
typing_extensions-4.4.0/src/test_typing_extensions.py
typing_extensions-4.4.0/src/typing_extensions.py
typing_extensions-4.4.0/PKG-INFO
```
### After
```
typing_extensions on  sdist-test via 🐍 v3.10.8
❯ python3 -m build .
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (flit_core >=3.4,<4)
* Getting dependencies for sdist...
* Building sdist...
* Building wheel from sdist
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (flit_core >=3.4,<4)
* Getting dependencies for wheel...
* Building wheel...
Successfully built typing_extensions-4.4.0.tar.gz and typing_extensions-4.4.0-py3-none-any.whl

typing_extensions on  sdist-test via 🐍 v3.10.8 took 4s
❯ tar tzf dist/typing_extensions-4.4.0.tar.gz
typing_extensions-4.4.0/CHANGELOG.md
typing_extensions-4.4.0/LICENSE
typing_extensions-4.4.0/README.md
typing_extensions-4.4.0/pyproject.toml
typing_extensions-4.4.0/src/_typed_dict_test_helper.py
typing_extensions-4.4.0/src/test_typing_extensions.py
typing_extensions-4.4.0/src/typing_extensions.py
typing_extensions-4.4.0/PKG-INFO
```

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
The CI failures are a little mysterious but seem unrelated to this change. I don't have time right now to investigate though.

The change in the PR looks good, thanks!

**Comment by hegjon** [comment]
Yes, the CI seems to fail during setup and not for this PR

**Comment by AlexWaygood** [comment]
This might be related: https://twitter.com/hynek/status/1596039449909264385?s=20&t=6k0Z5-nKmqIpXT25e0G-mg

**Comment by hegjon** [comment]
Did a new tiny PR #98 to see if the same CI issues happens on that too

**Comment by hegjon** [comment]
> This might be related: https://twitter.com/hynek/status/1596039449909264385?s=20&t=6k0Z5-nKmqIpXT25e0G-mg

Maybe `ubuntu-latest` changed from 20.04 to 22.04?

**Comment by hegjon** [comment]
Made issue #99 with more details

**Pull request merged**
